services:
  flask:
    image: flask-logo
    build:
      context: .
      dockerfile: Dockerfile

    environment:
      DB_NAME: ${DB_NAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USER: ${DB_USER}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}

      MINIO_HOST: ${MINIO_HOST}
      MINIO_API_PORT: ${MINIO_API_PORT}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_DEFAULT_BUCKET_NAME: ${MINIO_DEFAULT_BUCKET_NAME}

      TEMP_DIR_PATH: ${TEMP_DIR_PATH}

      TWEEPY_BEARER_TOKEN_MAIN: ${TWEEPY_BEARER_TOKEN_MAIN}
      TWEEPY_API_KEY_MAIN: ${TWEEPY_API_KEY_MAIN}
      TWEEPY_API_SECRET_MAIN: ${TWEEPY_API_SECRET_MAIN}
      TWEEPY_ACCESS_TOKEN_MAIN: ${TWEEPY_ACCESS_TOKEN_MAIN}
      TWEEPY_ACCESS_TOKEN_SECRET_MAIN: ${TWEEPY_ACCESS_TOKEN_SECRET_MAIN}

      TWEEPY_BEARER_TOKEN_ALT: ${TWEEPY_BEARER_TOKEN_ALT}
      TWEEPY_API_KEY_ALT: ${TWEEPY_API_KEY_ALT}
      TWEEPY_API_SECRET_ALT: ${TWEEPY_API_SECRET_ALT}
      TWEEPY_ACCESS_TOKEN_ALT: ${TWEEPY_ACCESS_TOKEN_ALT}
      TWEEPY_ACCESS_TOKEN_SECRET_ALT: ${TWEEPY_ACCESS_TOKEN_SECRET_ALT}

    command: ["flask", "run", "--host=0.0.0.0"]
    ports:
      - 5000:5000
    hostname: flask
    volumes:
      - /root/logo-recognition-project/model:/app/model
    depends_on:
      - postgres
    
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  postgres-data:
  pgadmin-data: