name: deploy-flask
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Docker compose down
        run: |
          COMPOSE_STATUS=$(docker compose ps -q)
          if [ -z "$COMPOSE_STATUS" ]; then
            echo "Docker Compose is not running"
          else
            docker compose down
          fi

      - name: Prune Unused Images
        run: docker image prune -f

      - name: Create .env File
        run: |
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DB_USER=${{ secrets.DB_USER }}" >> .env
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env

          echo "PGADMIN_DEFAULT_EMAIL=${{ secrets.PGADMIN_DEFAULT_EMAIL }}" >> .env
          echo "PGADMIN_DEFAULT_PASSWORD=${{ secrets.PGADMIN_DEFAULT_PASSWORD }}" >> .env

          echo "MINIO_HOST=${{ secrets.MINIO_HOST }}" >> .env
          echo "MINIO_API_PORT=${{ secrets.MINIO_API_PORT }}" >> .env
          echo "MINIO_ACCESS_KEY=${{ secrets.MINIO_ACCESS_KEY }}" >> .env
          echo "MINIO_SECRET_KEY=${{ secrets.MINIO_SECRET_KEY }}" >> .env
          echo "MINIO_DEFAULT_BUCKET_NAME=${{ secrets.MINIO_DEFAULT_BUCKET_NAME }}" >> .env

          echo "TEMP_DIR_PATH=${{ secrets.TEMP_DIR_PATH }}" >> .env

          echo "TWEEPY_BEARER_TOKEN_MAIN=${{ secrets.TWEEPY_BEARER_TOKEN_MAIN }}" >> .env
          echo "TWEEPY_API_KEY_MAIN=${{ secrets.TWEEPY_API_KEY_MAIN }}" >> .env
          echo "TWEEPY_API_SECRET_MAIN=${{ secrets.TWEEPY_API_SECRET_MAIN }}" >> .env
          echo "TWEEPY_ACCESS_TOKEN_MAIN=${{ secrets.TWEEPY_ACCESS_TOKEN_MAIN }}" >> .env
          echo "TWEEPY_ACCESS_TOKEN_SECRET_MAIN=${{ secrets.TWEEPY_ACCESS_TOKEN_SECRET_MAIN }}" >> .env

          echo "TWEEPY_BEARER_TOKEN_ALT=${{ secrets.TWEEPY_BEARER_TOKEN_ALT }}" >> .env
          echo "TWEEPY_API_KEY_ALT=${{ secrets.TWEEPY_API_KEY_ALT }}" >> .env
          echo "TWEEPY_API_SECRET_ALT=${{ secrets.TWEEPY_API_SECRET_ALT }}" >> .env
          echo "TWEEPY_ACCESS_TOKEN_ALT=${{ secrets.TWEEPY_ACCESS_TOKEN_ALT }}" >> .env
          echo "TWEEPY_ACCESS_TOKEN_SECRET_ALT=${{ secrets.TWEEPY_ACCESS_TOKEN_SECRET_ALT }}" >> .env

          echo "TWEEPY_BEARER_TOKEN_ALT_1=${{ secrets.TWEEPY_BEARER_TOKEN_ALT_1 }}" >> .env
          echo "TWEEPY_API_KEY_ALT_1=${{ secrets.TWEEPY_API_KEY_ALT_1 }}" >> .env
          echo "TWEEPY_API_SECRET_ALT_1=${{ secrets.TWEEPY_API_SECRET_ALT_1 }}" >> .env
          echo "TWEEPY_ACCESS_TOKEN_ALT_1=${{ secrets.TWEEPY_ACCESS_TOKEN_ALT_1 }}" >> .env
          echo "TWEEPY_ACCESS_TOKEN_SECRET_ALT_1=${{ secrets.TWEEPY_ACCESS_TOKEN_SECRET_ALT_1 }}" >> .env

          echo "TWEEPY_BEARER_TOKEN_ALT_2=${{ secrets.TWEEPY_BEARER_TOKEN_ALT_2 }}" >> .env
          echo "TWEEPY_API_KEY_ALT_2=${{ secrets.TWEEPY_API_KEY_ALT_2 }}" >> .env
          echo "TWEEPY_API_SECRET_ALT_2=${{ secrets.TWEEPY_API_SECRET_ALT_2 }}" >> .env
          echo "TWEEPY_ACCESS_TOKEN_ALT_2=${{ secrets.TWEEPY_ACCESS_TOKEN_ALT_2 }}" >> .env
          echo "TWEEPY_ACCESS_TOKEN_SECRET_ALT_2=${{ secrets.TWEEPY_ACCESS_TOKEN_SECRET_ALT_2 }}" >> .env

          echo "TWEEPY_BEARER_TOKEN_ALT_3=${{ secrets.TWEEPY_BEARER_TOKEN_ALT_3 }}" >> .env
          echo "TWEEPY_API_KEY_ALT_3=${{ secrets.TWEEPY_API_KEY_ALT_3 }}" >> .env
          echo "TWEEPY_API_SECRET_ALT_3=${{ secrets.TWEEPY_API_SECRET_ALT_3 }}" >> .env
          echo "TWEEPY_ACCESS_TOKEN_ALT_3=${{ secrets.TWEEPY_ACCESS_TOKEN_ALT_3 }}" >> .env
          echo "TWEEPY_ACCESS_TOKEN_SECRET_ALT_3=${{ secrets.TWEEPY_ACCESS_TOKEN_SECRET_ALT_3 }}" >> .env

          echo "TWEEPY_BEARER_TOKEN_ALT_4=${{ secrets.TWEEPY_BEARER_TOKEN_ALT_4 }}" >> .env
          echo "TWEEPY_API_KEY_ALT_4=${{ secrets.TWEEPY_API_KEY_ALT_4 }}" >> .env
          echo "TWEEPY_API_SECRET_ALT_4=${{ secrets.TWEEPY_API_SECRET_ALT_4 }}" >> .env
          echo "TWEEPY_ACCESS_TOKEN_ALT_4=${{ secrets.TWEEPY_ACCESS_TOKEN_ALT_4 }}" >> .env
          echo "TWEEPY_ACCESS_TOKEN_SECRET_ALT_4=${{ secrets.TWEEPY_ACCESS_TOKEN_SECRET_ALT_4 }}" >> .env

      - name: Verify .env File
        run: cat .env

      - name: Docker Compose Up And Build Images
        run: docker compose up -d --build
